"""Enumerations for internship workflow."""

import enum


class InternshipStatus(enum.Enum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"


class EnrollmentStatus(enum.Enum):
    PENDING = "PENDING"
    AWAITING_APPROVAL = "AWAITING_APPROVAL"
    REVISION_REQUIRED = "REVISION_REQUIRED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    REJECTED = "REJECTED"
    COMMISSION_REVIEW = "COMMISSION_REVIEW"
    DIRECTOR_APPROVAL = "DIRECTOR_APPROVAL"


class InternshipPath(enum.Enum):
    STANDARD = "STANDARD"
    EMPLOYMENT = "EMPLOYMENT"
    OWN_BUSINESS = "OWN_BUSINESS"


class EventType(enum.Enum):
    ADMIN_COMMENT = "ADMIN_KOMENTARZ"
    SUPERVISOR_COMMENT = "UOPZ_KOMENTARZ"
    STUDENT_NOTIFICATION = "POWIADOMIENIE_STUDENTA"
    COMMITTEE_DECISION = "KOMISJA_DECYZJA"
    DIRECTOR_DECISION = "DYREKTOR_DECYZJA"
